title: J0LGER - Bloghub
email: majd.jolger@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Obsessed with breaking stuff | Web & InfoSec. 
twitter_username: jolger16
github_username:  J0LGER
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile